### ISSUE TITLE
Darwin prebuilts for node

### ISSUE THREAD

**Issue by coderaiser** [daviwil/node-pty-prebuilt#1]
Thank you for great realisation of  prebuilts.
Could you please add `darwin` binaries for `node.js` :)?

**Comment by daviwil** [comment]
Yep!  I had a TravisCI build going for that last night but it failed due to a silly syntax error.  I'll restart the run in a moment and the prebuilt binaries should be uploaded after that.

**Comment by daviwil** [comment]
Actually it looks like the Darwin prebuilts got uploaded

https://github.com/daviwil/node-pty-prebuilt/releases/tag/v0.7.3

Try installing the module again and let me know if it works for you!

**Comment by coderaiser** [comment]
Yes, it works, thank you.
