### ISSUE TITLE
Node v10 support

### ISSUE THREAD

**Issue by coderaiser** [daviwil/node-pty-prebuilt#2]
Could you please add binaries for `node v10`:

```
 node-pty-prebuilt@0.7.3 install /home/travis/build/[secure]/cloudcmd/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js
prebuild-install WARN install No prebuilt binaries found (target=10.1.0 runtime=node arch=x64 platform=linux)
```

**Comment by daviwil** [comment]
There are binaries up for Node 10 on Linux with version 0.7.5 now, still working on getting the Windows binaries uploaded.

**Comment by daviwil** [comment]
v0.7.6 is out now with Node 10 support: https://github.com/daviwil/node-pty-prebuilt/releases/tag/v0.7.6
