### ISSUE TITLE
New Release with prebuild-install 4.0

### ISSUE THREAD

**Issue by pfitzseb** [daviwil/node-pty-prebuilt#4]
prebuild-install 4.0.0 fixes a rather annoying bug when installing on filesystems with short maximum file name lengths (e.g. Ubuntu with disk encryption): https://github.com/prebuild/prebuild-install/issues/77

Downstream issue: https://github.com/JunoLab/atom-julia-client/issues/440

Would be great if you could tag a new release with that fix :) Let me know if there's anything I can do to help.

**Comment by pfitzseb** [comment]
Bump :)

**Comment by daviwil** [comment]
v0.7.6 is out, I bumped it to prebuild-install 5.0.0:  https://github.com/daviwil/node-pty-prebuilt/releases/tag/v0.7.6

**Comment by pfitzseb** [comment]
Thank you, much appreciated :)
