### ISSUE TITLE
Windows binaries for 0.75

### ISSUE THREAD

**Issue by ak239** [daviwil/node-pty-prebuilt#5]
## Environment details

- OS: Windows
- OS version: 10
- node-pty version: 0.75

## Issue description

On releases tab I can find different win32 binaries for 0.73 but nothing windows related for 0.75. Is it expected?

Thanks for your work!

**Comment by the-j0k3r** [comment]
The builds for windows are all failing atm https://ci.appveyor.com/project/daviwil/node-pty-prebuilt/build/1.0.18

I guess we have to wait until this becomes high enough priority to be looked at ;)

**Comment by the-j0k3r** [comment]
node-pty is now at version 0.7.6 still no Windows builds here.

**Comment by daviwil** [comment]
v0.7.6 is out!  https://github.com/daviwil/node-pty-prebuilt/releases/tag/v0.7.6
