### ISSUE TITLE
Publish version 0.7.5

### ISSUE THREAD

**Issue by somebee** [daviwil/node-pty-prebuilt#7]
Hope you'll be able to push v0.7.5 to npm soon! 👍

**Comment by faressoft** [comment]
Me too

**Comment by the-j0k3r** [comment]
@daviwil node-pty has released version 0.7.6 on 21st June which would supersede this request.
There are still no Windows builds for 0.7.3.

**Comment by daviwil** [comment]
v0.7.6 is out!  https://github.com/daviwil/node-pty-prebuilt/releases/tag/v0.7.6

**Comment by faressoft** [comment]
@daviwil You made my day 👍 Thanks man !
