### ISSUE TITLE
Cannot find module '../build/Release/pty.node'

### ISSUE THREAD

**Issue by jfrux** [daviwil/node-pty-prebuilt#8]
## Environment details

- OS: MacOS
- OS version: 10.14
- node-pty version: 0.7.6

## Issue description
Electron builds keep saying:
![image](https://user-images.githubusercontent.com/171077/47454242-bb2da180-d79c-11e8-9631-6e862a9d15ce.png)

**Comment by daviwil** [comment]
Judging from the `app/node_modules/node-pty` path in your stack trace, it looks like you're using `node-pty` and not `node-pty-prebuilt`.  I'd suggest filing this issue over at the main repo:

https://github.com/Microsoft/node-pty

**Comment by jfrux** [comment]
Well that wasn’t my intent…
Was trying to use the prebuilt package… when I specify node-pty for require() and for package.json it builds… but I have to build on each platform separately.
Was hoping to avoid this by switching require() and package.json to point to prebuilt version but when I do I get the missing message.

Thank you for your response so quickly!

**Comment by jfrux** [comment]
OMG I'm so sorry... so I had a dependency I wasn't using... `default-shell` and it was referencing node-pty even tho my project wasn't.

Very sorry and thank you again for your time.

**Comment by daviwil** [comment]
No problem at all!  Glad you were able to get it figured out :smile:
